alias c="open $1 -a \"Visual Studio Code\""

alias p="cd ~/Projects"

# reinstall next.js app
alias rna="rm -rf node_modules yarn.lock .next && yarn install"

# git
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gpl="git pull"
alias gp="git push"
alias gs="git status"

# yarn
alias ya="yarn add"
alias yb="yarn build"
alias yd="yarn dev"
alias yi="yarn install"
alias yl="yarn lint"
alias ylf="yarn lint:fix"
alias yr="yarn remove"
alias yu="yarn upgrade-interactive --latest"