export PATH="/opt/homebrew/opt/node@18/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

export LDFLAGS="-L/opt/homebrew/opt/node@18/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@18/include"

alias c="open $1 -a \"Visual Studio Code\""

alias p="cd ~/Projects"

# reinstall next.js app
alias rna="rm -rf node_modules yarn.lock .next && yarn install"

# git
alias ga="git add"
alias gb="git branch"
alias gc="git commit"
alias gpl="git pull"
alias gp="git push"
alias gs="git status"

# yarn
alias ya="yarn add"
alias yb="yarn build"
alias yd="yarn dev"
alias yi="yarn install"
alias yl="yarn lint"
alias ylf="yarn lint:fix"
alias yr="yarn remove"
alias yu="yarn upgrade-interactive --latest"

# brew
alias bu="brew update && brew upgrade && brew cleanup && brew doctor"
alias bbd="brew bundle dump --force"

# ip
alias ip="ifconfig -l | xargs -n1 ipconfig getifaddr"
alias ipv4="dig @resolver1.opendns.com A myip.opendns.com +short -4"
alias ipv6="dig @resolver1.opendns.com AAAA myip.opendns.com +short -6"export PATH="/opt/homebrew/opt/node@18/bin:$PATH"
