tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "planetscale/tap"

brew "gh"
brew "mysql-client"
brew "node@16"
brew "python@3.9"
brew "planetscale/tap/pscale"

cask "alt-tab"
cask "anydesk"
cask "brave-browser"
cask "discord"
cask "dockmate"
cask "imageoptim"
cask "iina"
cask "messenger"
cask "mongodb-compass"
cask "rectangle"
cask "spotify"
cask "stats"
cask "visual-studio-code"
